# fixing position by Grid Table
- result_name = "csv file that only interpolated"
- df_result_raw = "csv file that done by Grid Table"
- steps = how big cells are

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

date ="0507" #0611 0514 0507
#result_name = "Result-0709-#2_enter_10min_late-Fin.csv"
#result_name = "Result-0604-#10-21120_25179-Fin.csv"
result_name ="Result-"+date+"-Fin.csv"
df_result_raw = "withGrid_"+date+".csv"

In [3]:
df = pd.read_csv(result_name)

# pd.options.display.max_rows = 60
# pd.options.display.max_columns = 20
df_x=df[['1_X', '2_X',  '3_X', '4_X', '5_X',  '6_X', '7_X', '8_X', 
       '9_X', '10_X', '11_X',  '12_X', '13_X', '14_X', '15_X', '16_X']]
df_y=df[[ '1_Y',  '2_Y',  '3_Y', '4_Y', '5_Y',  '6_Y',  '7_Y', '8_Y',
       '9_Y','10_Y', '11_Y',  '12_Y', '13_Y', '14_Y', '15_Y',  '16_Y']]

In [ ]:
#Griding X position


#1920×1080
steps=2
x_grid =np.arange(0, 1920, step=steps)
y_grid =np.arange(0, 1080, step=steps)
# 이전 프레임의 값을 고정해두고, 그 값이 속해있던 그리드를 벗어나면 그 값으로 다시 초기화 하는 방식.
for i in df_x.columns:
    c=0
    g=0
    print(i)
    for index in range(df["1_X"].size): 
        if(index==0):
            for grid in x_grid:
                if (df_x[i][index]>=grid and df_x[i][index]<(grid+steps)):
                    c=df_x[i][index]
                    g=grid
                    break
        else:
            for grid in x_grid:
                if (df_x[i][index]>=grid and df_x[i][index]<(grid+steps)):
                    if (g==grid) :
                        df_x[i][index]=c
                        break
                    else :
                        c=df_x[i][index]
                        g=grid
                        break

1_X

C:\Users\82108\AppData\Local\Temp/ipykernel_4940/1898572540.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_x[i][index]=c

In [3]:

# Griding Y position

for i in df_y.columns:
    c=0
    g=0
    print(i)
    for index in range(df["1_Y"].size):
        if(index==0):
            for grid in y_grid:
                if (df_y[i][index]>=grid and df_y[i][index]<(grid+steps)):
                    c=df_y[i][index]
                    g=grid
                    break
        else:
            for grid in y_grid:
                if (df_y[i][index]>=grid and df_y[i][index]<(grid+steps)):
                    if (g==grid) :
                        df_y[i][index]=c
                        break
                    else :
                        c=df_y[i][index]
                        g=grid
                        break

1_Y

C:\Users\82108\AppData\Local\Temp/ipykernel_2160/1009793327.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_y[i][index]=c

2_Y
3_Y
4_Y
5_Y
6_Y
7_Y
8_Y
9_Y
10_Y
11_Y
12_Y
13_Y
14_Y
15_Y
16_Y

In [7]:
#concat X and Y position, also adding frameNum
result = pd.concat([df_x,df_y],axis=1)
result["frameNum"] = df["frameNum"]
result = result.reindex(columns=["frameNum","1_X", "1_Y","2_X", "2_Y" 
                                     ,"3_X", "3_Y" ,"4_X", "4_Y" 
                                     ,"5_X", "5_Y" ,"6_X", "6_Y" 
                                     ,"7_X", "7_Y" ,"8_X", "8_Y" 
                                     ,"9_X", "9_Y" ,"10_X", "10_Y" 
                                     ,"11_X", "11_Y" ,"12_X", "12_Y" 
                                     ,"13_X", "13_Y" ,"14_X", "14_Y" 
                                     ,"15_X", "15_Y" ,"16_X", "16_Y" ])
result[["nc1", "nc2", "nc3", "nc4", "nc5", "nc6", "nc7", "nc8", 
        "nc9", "nc10", "nc11", "nc12", "nc13", "nc14", "nc15", "nc16"]]= df[["nc1", "nc2", "nc3", "nc4", "nc5", "nc6", "nc7", "nc8", 
                                                                             "nc9", "nc10", "nc11", "nc12", "nc13", "nc14", "nc15", "nc16"]]
print(result)
result.to_csv(df_result_raw)

       frameNum     1_X    1_Y     2_X    2_Y          3_X         3_Y  \
0            76  1127.0  810.0  1233.0  383.0  1301.000000  530.000000
1            77  1127.0  810.0  1233.0  385.0  1303.000000  532.000000
2            78  1127.0  810.0  1242.0  405.0  1303.000000  531.000000
3            79  1127.0  810.0  1239.0  400.0  1305.000000  534.000000
4            80  1127.0  810.0  1233.0  382.0  1307.000000  540.000000
...         ...     ...    ...     ...    ...          ...         ...
62273     62349  1380.0  539.0   986.0  717.0  1302.867821  740.535805
62274     62350  1380.0  539.0   991.0  718.0  1306.650718  740.651820
62275     62351  1380.0  539.0  1007.0  720.0  1310.433616  740.767835
62276     62352  1380.0  539.0  1012.0  721.0  1314.216513  740.883850
62277     62353  1379.0  540.0  1003.0  719.0  1318.000000  741.000000

          4_X    4_Y     5_X  ...    nc7    nc8    nc9   nc10   nc11   nc12  \
0      1344.0  600.0  1371.0  ...   True  False  False  False  False  False
1      1344.0  600.0  1371.0  ...   True  False  False  False  False  False
2      1344.0  601.0  1371.0  ...   True  False  False  False  False  False
3      1343.0  601.0  1370.0  ...   True  False  False  False  False  False
4      1342.0  599.0  1370.0  ...   True  False  False  False  False  False
...       ...    ...     ...  ...    ...    ...    ...    ...    ...    ...
62273  1347.0  607.0   506.0  ...  False  False  False  False   True  False
62274  1347.0  607.0   510.0  ...  False  False  False  False   True  False
62275  1346.0  604.0   505.0  ...  False  False  False  False   True  False
62276  1347.0  604.0   501.0  ...  False  False  False  False   True  False
62277  1349.0  608.0   501.0  ...  False  False  False  False   True  False

        nc13   nc14  nc15  nc16
0      False  False  True  True
1      False  False  True  True
2      False  False  True  True
3      False  False  True  True
4      False  False  True  True
...      ...    ...   ...   ...
62273  False  False  True  True
62274  False  False  True  True
62275  False  False  True  True
62276  False  False  True  True
62277  False  False  True  True

[62278 rows x 49 columns]

In [8]:
#show result dataframe
result

,frameNum,1_X,1_Y,2_X,2_Y,3_X,3_Y,4_X,4_Y,5_X,...,nc7,nc8,nc9,nc10,nc11,nc12,nc13,nc14,nc15,nc16
0,76,1127.0,810.0,1233.0,383.0,1301.000000,530.000000,1344.0,600.0,1371.0,...,True,False,False,False,False,False,False,False,True,True
1,77,1127.0,810.0,1233.0,385.0,1303.000000,532.000000,1344.0,600.0,1371.0,...,True,False,False,False,False,False,False,False,True,True
2,78,1127.0,810.0,1242.0,405.0,1303.000000,531.000000,1344.0,601.0,1371.0,...,True,False,False,False,False,False,False,False,True,True
3,79,1127.0,810.0,1239.0,400.0,1305.000000,534.000000,1343.0,601.0,1370.0,...,True,False,False,False,False,False,False,False,True,True
4,80,1127.0,810.0,1233.0,382.0,1307.000000,540.000000,1342.0,599.0,1370.0,...,True,False,False,False,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62273,62349,1380.0,539.0,986.0,717.0,1302.867821,740.535805,1347.0,607.0,506.0,...,False,False,False,False,True,False,False,False,True,True
62274,62350,1380.0,539.0,991.0,718.0,1306.650718,740.651820,1347.0,607.0,510.0,...,False,False,False,False,True,False,False,False,True,True
62275,62351,1380.0,539.0,1007.0,720.0,1310.433616,740.767835,1346.0,604.0,505.0,...,False,False,False,False,True,False,False,False,True,True
62276,62352,1380.0,539.0,1012.0,721.0,1314.216513,740.883850,1347.0,604.0,501.0,...,False,False,False,False,True,False,False,False,True,True
62277,62353,1379.0,540.0,1003.0,719.0,1318.000000,741.000000,1349.0,608.0,501.0,...,False,False,False,False,True,False,False,False,True,True